// @generated by scripts/sync-design-tokens.mjs from design-tokens.json — do not edit.
// Run `just sync-tokens` after editing design-tokens.json.
import Foundation

/// Canonical Hakka color tokens (hex), shared with RN + Android.
enum HakkaTokens {
    static let statusSuccess: UInt32 = 0x3AA981
    static let statusInfo: UInt32 = 0x6D9BC9
    static let statusWarning: UInt32 = 0xD9A514
    static let statusError: UInt32 = 0xE2554A
    static let statusPending: UInt32 = 0x8D8778
    static let statusOn: UInt32 = 0xFFFFFF
    static let statusOnWarm: UInt32 = 0x171310
    static let methodGet: UInt32 = 0x3AA981
    static let methodPost: UInt32 = 0xEE8320
    static let methodPut: UInt32 = 0x6D9BC9
    static let methodPatch: UInt32 = 0xA87FC4
    static let methodDelete: UInt32 = 0xE2554A
    static let methodOther: UInt32 = 0x8D8778
    static let timingDns: UInt32 = 0x6D9BC9
    static let timingTcp: UInt32 = 0x4FB3A3
    static let timingTls: UInt32 = 0x3AA981
    static let timingTtfb: UInt32 = 0xD9A514
    static let timingDownload: UInt32 = 0xEE8320
    static let darkBackground: UInt32 = 0x121110
    static let darkSurface: UInt32 = 0x1A1816
    static let darkSurfaceRaised: UInt32 = 0x23201C
    static let darkBorder: UInt32 = 0x35302A
    static let darkText: UInt32 = 0xEDEAE4
    static let darkTextSecondary: UInt32 = 0xA8A296
    static let darkTextTertiary: UInt32 = 0x6E695F
    static let darkAccent: UInt32 = 0xEE8320
    static let lightBackground: UInt32 = 0xFAF8F4
    static let lightSurface: UInt32 = 0xF2EFE8
    static let lightSurfaceRaised: UInt32 = 0xFFFFFF
    static let lightBorder: UInt32 = 0xE2DDD2
    static let lightText: UInt32 = 0x21201C
    static let lightTextSecondary: UInt32 = 0x57534A
    static let lightTextTertiary: UInt32 = 0x8B857A
    static let lightAccent: UInt32 = 0xE0761A
    static let codeDarkKey: UInt32 = 0xA8A296
    static let codeDarkString: UInt32 = 0xDE8D68
    static let codeDarkNumber: UInt32 = 0x7FB3E8
    static let codeDarkBoolean: UInt32 = 0xC08FD9
    static let codeDarkNull: UInt32 = 0xC08FD9
    static let codeDarkHighlight: UInt32 = 0x4D3D10
    static let codeLightKey: UInt32 = 0x57534A
    static let codeLightString: UInt32 = 0xB4552A
    static let codeLightNumber: UInt32 = 0x2B6CB0
    static let codeLightBoolean: UInt32 = 0x8548AB
    static let codeLightNull: UInt32 = 0x8548AB
    static let codeLightHighlight: UInt32 = 0xF5E5C0
}

/// Canonical Hakka geometry, shared with RN + web + Android. Every interactive
/// control's height comes from ControlHeight; every page edge from
/// Layout.gutter. See DESIGN.md "One geometry".
///
/// public: the macOS app (a separate SPM module, HakkaApp) reaches for this
/// type directly — unlike HakkaTokens/Theme's colors, these are bare CGFloat
/// constants with no UIKit dependency, so there is no reason to fork a second
/// copy the way emitSwiftDesktop() has to for colors. See
/// apps/hakka/Sources/App/Helpers/Metrics.swift for the desktop's short
/// aliases onto this.
public enum HakkaMetrics {
    public enum Spacing {
        public static let xxs: CGFloat = 2
        public static let xs: CGFloat = 4
        public static let sm: CGFloat = 6
        public static let md: CGFloat = 8
        public static let ml: CGFloat = 10
        public static let lg: CGFloat = 12
        public static let ll: CGFloat = 14
        public static let xl: CGFloat = 16
        public static let xxl: CGFloat = 20
        public static let xxxl: CGFloat = 24
    }

    public enum Radius {
        public static let xs: CGFloat = 2
        public static let sm: CGFloat = 4
        public static let md: CGFloat = 6
        public static let lg: CGFloat = 10
        public static let xl: CGFloat = 14
        public static let pill: CGFloat = 999
    }

    public enum FontSize {
        public static let xxs: CGFloat = 9
        public static let xs: CGFloat = 10
        public static let sm: CGFloat = 12
        public static let md: CGFloat = 13
        public static let lg: CGFloat = 15
        public static let xl: CGFloat = 16
        public static let xxl: CGFloat = 18
        public static let display: CGFloat = 22
        public static let hero: CGFloat = 26
    }

    public enum ControlHeight {
        public static let badge: CGFloat = 18
        public static let chip: CGFloat = 24
        public static let icon: CGFloat = 28
        public static let md: CGFloat = 28
        public static let field: CGFloat = 36
        public static let nav: CGFloat = 40
        public static let bar: CGFloat = 44
    }

    public enum Layout {
        public static let gutter: CGFloat = 16
        public static let cardPadding: CGFloat = 12
        public static let sectionGap: CGFloat = 16
        public static let rowGap: CGFloat = 8
    }
}
