// @ts-nocheck -- oxfmt loads this directly via the npm package runtime
export default {
  semi: false,
  singleQuote: true,
  printWidth: 120,
  tabWidth: 2,
  trailingComma: 'all',
  sortImports: {},
  sortPackageJson: true,
  // packages/hakka-browser/src/ui/tokens.css is @generated by sync-design-tokens.mjs and
  // gated by `sync-tokens --check`; the formatter must not rewrite it.
  ignorePatterns: [
    '**/node_modules',
    '**/dist',
    '**/lib',
    // …but docs/src/lib is committed source (the hand-authored icon module
    // HakkaIcon.astro imports), not build output — format it like the rest.
    '!docs/src/lib',
    '**/build',
    '**/.build',
    'packages/hakka-browser/src/ui/tokens.css',
    // Vendored, minified hakka-browser bundle for the docs hero/demo embed (refresh via `just sync-embed`).
    'docs/public/embed',
    // Same for the generated hakka-browser/elements bundles (refresh via `just sync-embed-components`).
    'docs/public/embed-components',
    // Next.js rewrites these on every `next dev`/`next build` in its own style; formatting them just churns.
    'examples/next-fullstack/next-env.d.ts',
    'examples/next-fullstack/tsconfig.json',
  ],
}
