// @generated by scripts/sync-design-tokens.mjs from design-tokens.json — do not edit.
// Run `just sync-tokens` after editing design-tokens.json.
import AppKit
import SwiftUI

/// Canonical Hakka color tokens for the macOS app — same source as the four
/// inspector platforms. Data only; status/method/timing mappings live in Fmt.
enum ThemeTokens {
    /// Semantic status text colors resolve against the active macOS appearance.
    enum Status {
        private static func adaptive(light: NSColor, dark: NSColor) -> Color {
            Color(nsColor: NSColor(name: nil) { appearance in
                appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua ? dark : light
            })
        }

        static let success = adaptive(light: NSColor(srgbRed: 0.0902, green: 0.4510, blue: 0.3098, alpha: 1), dark: NSColor(srgbRed: 0.2275, green: 0.6627, blue: 0.5059, alpha: 1))
        static let info = adaptive(light: NSColor(srgbRed: 0.1961, green: 0.3804, blue: 0.5608, alpha: 1), dark: NSColor(srgbRed: 0.4275, green: 0.6078, blue: 0.7882, alpha: 1))
        static let warning = adaptive(light: NSColor(srgbRed: 0.5020, green: 0.3765, blue: 0.0000, alpha: 1), dark: NSColor(srgbRed: 0.8510, green: 0.6471, blue: 0.0784, alpha: 1))
        static let error = adaptive(light: NSColor(srgbRed: 0.6863, green: 0.1882, blue: 0.1647, alpha: 1), dark: NSColor(srgbRed: 0.8863, green: 0.3333, blue: 0.2902, alpha: 1))
        static let pending = adaptive(light: NSColor(srgbRed: 0.3843, green: 0.3686, blue: 0.3294, alpha: 1), dark: NSColor(srgbRed: 0.5529, green: 0.5294, blue: 0.4706, alpha: 1))
        static let on = Color(nsColor: NSColor(srgbRed: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1))
        static let onWarm = Color(nsColor: NSColor(srgbRed: 0.0902, green: 0.0745, blue: 0.0627, alpha: 1))
    }

    /// HTTP method text colors resolve against the active macOS appearance.
    enum Method {
        private static func adaptive(light: NSColor, dark: NSColor) -> Color {
            Color(nsColor: NSColor(name: nil) { appearance in
                appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua ? dark : light
            })
        }

        static let get = adaptive(light: NSColor(srgbRed: 0.0902, green: 0.4510, blue: 0.3098, alpha: 1), dark: NSColor(srgbRed: 0.2275, green: 0.6627, blue: 0.5059, alpha: 1))
        static let post = adaptive(light: NSColor(srgbRed: 0.6314, green: 0.3098, blue: 0.0000, alpha: 1), dark: NSColor(srgbRed: 0.9333, green: 0.5137, blue: 0.1255, alpha: 1))
        static let put = adaptive(light: NSColor(srgbRed: 0.1961, green: 0.3804, blue: 0.5608, alpha: 1), dark: NSColor(srgbRed: 0.4275, green: 0.6078, blue: 0.7882, alpha: 1))
        static let patch = adaptive(light: NSColor(srgbRed: 0.4588, green: 0.2510, blue: 0.5569, alpha: 1), dark: NSColor(srgbRed: 0.6588, green: 0.4980, blue: 0.7686, alpha: 1))
        static let delete = adaptive(light: NSColor(srgbRed: 0.6863, green: 0.1882, blue: 0.1647, alpha: 1), dark: NSColor(srgbRed: 0.8863, green: 0.3333, blue: 0.2902, alpha: 1))
        static let other = adaptive(light: NSColor(srgbRed: 0.3843, green: 0.3686, blue: 0.3294, alpha: 1), dark: NSColor(srgbRed: 0.5529, green: 0.5294, blue: 0.4706, alpha: 1))
    }

    enum Timing {
        static let dns = Color(red: 0.4275, green: 0.6078, blue: 0.7882)
        static let tcp = Color(red: 0.3098, green: 0.7020, blue: 0.6392)
        static let tls = Color(red: 0.2275, green: 0.6627, blue: 0.5059)
        static let ttfb = Color(red: 0.8510, green: 0.6471, blue: 0.0784)
        static let download = Color(red: 0.9333, green: 0.5137, blue: 0.1255)
    }

    /// JSON syntax colors resolve against the active macOS appearance.
    enum Code {
        private static func adaptive(light: NSColor, dark: NSColor) -> Color {
            Color(nsColor: NSColor(name: nil) { appearance in
                appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua ? dark : light
            })
        }

        static let key = adaptive(light: NSColor(srgbRed: 0.3412, green: 0.3255, blue: 0.2902, alpha: 1), dark: NSColor(srgbRed: 0.6588, green: 0.6353, blue: 0.5882, alpha: 1))
        static let string = adaptive(light: NSColor(srgbRed: 0.7059, green: 0.3333, blue: 0.1647, alpha: 1), dark: NSColor(srgbRed: 0.8706, green: 0.5529, blue: 0.4078, alpha: 1))
        static let number = adaptive(light: NSColor(srgbRed: 0.1686, green: 0.4235, blue: 0.6902, alpha: 1), dark: NSColor(srgbRed: 0.4980, green: 0.7020, blue: 0.9098, alpha: 1))
        static let boolean = adaptive(light: NSColor(srgbRed: 0.5216, green: 0.2824, blue: 0.6706, alpha: 1), dark: NSColor(srgbRed: 0.7529, green: 0.5608, blue: 0.8510, alpha: 1))
        static let null = adaptive(light: NSColor(srgbRed: 0.5216, green: 0.2824, blue: 0.6706, alpha: 1), dark: NSColor(srgbRed: 0.7529, green: 0.5608, blue: 0.8510, alpha: 1))
        static let highlight = adaptive(light: NSColor(srgbRed: 0.9608, green: 0.8980, blue: 0.7529, alpha: 1), dark: NSColor(srgbRed: 0.3020, green: 0.2392, blue: 0.0627, alpha: 1))
    }
}
