// @generated by scripts/sync-design-tokens.mjs from design-tokens.json — do not edit.
// Run `just sync-tokens` after editing design-tokens.json.
import SwiftUI

/// Canonical Hakka color tokens for the macOS app — same source as the four
/// inspector platforms. Data only; status/method/timing mappings live in Fmt.
enum ThemeTokens {
    enum Status {
        static let success = Color(red: 0.2275, green: 0.6627, blue: 0.5059)
        static let info = Color(red: 0.4275, green: 0.6078, blue: 0.7882)
        static let warning = Color(red: 0.8510, green: 0.6471, blue: 0.0784)
        static let error = Color(red: 0.8863, green: 0.3333, blue: 0.2902)
        static let pending = Color(red: 0.5529, green: 0.5294, blue: 0.4706)
        static let on = Color(red: 1.0000, green: 1.0000, blue: 1.0000)
        static let onWarm = Color(red: 0.0902, green: 0.0745, blue: 0.0627)
    }

    enum Method {
        static let get = Color(red: 0.2275, green: 0.6627, blue: 0.5059)
        static let post = Color(red: 0.9333, green: 0.5137, blue: 0.1255)
        static let put = Color(red: 0.4275, green: 0.6078, blue: 0.7882)
        static let patch = Color(red: 0.6588, green: 0.4980, blue: 0.7686)
        static let delete = Color(red: 0.8863, green: 0.3333, blue: 0.2902)
        static let other = Color(red: 0.5529, green: 0.5294, blue: 0.4706)
    }

    enum Timing {
        static let dns = Color(red: 0.4275, green: 0.6078, blue: 0.7882)
        static let tcp = Color(red: 0.3098, green: 0.7020, blue: 0.6392)
        static let tls = Color(red: 0.2275, green: 0.6627, blue: 0.5059)
        static let ttfb = Color(red: 0.8510, green: 0.6471, blue: 0.0784)
        static let download = Color(red: 0.9333, green: 0.5137, blue: 0.1255)
    }

    // JSON syntax colors — codeDark only (this app has no adaptive
    // light/dark mirror yet, same call as Status/Method/Timing above).
    enum Code {
        static let key = Color(red: 0.6588, green: 0.6353, blue: 0.5882)
        static let string = Color(red: 0.8706, green: 0.5529, blue: 0.4078)
        static let number = Color(red: 0.4980, green: 0.7020, blue: 0.9098)
        static let boolean = Color(red: 0.7529, green: 0.5608, blue: 0.8510)
        static let null = Color(red: 0.7529, green: 0.5608, blue: 0.8510)
        static let highlight = Color(red: 0.3020, green: 0.2392, blue: 0.0627)
    }
}
