// @generated by scripts/sync-design-tokens.mjs from design-tokens.json — do not edit.
// Run `just sync-tokens` after editing design-tokens.json.
package com.noodleapps.hakka.ui

/** Canonical Hakka color tokens (hex strings), shared with RN + iOS. */
internal object GeneratedTokens {
    const val statusSuccess = "#3AA981"
    const val statusInfo = "#6D9BC9"
    const val statusWarning = "#D9A514"
    const val statusError = "#E2554A"
    const val statusPending = "#8D8778"
    const val statusOn = "#FFFFFF"
    const val statusOnWarm = "#171310"
    const val methodGet = "#3AA981"
    const val methodPost = "#EE8320"
    const val methodPut = "#6D9BC9"
    const val methodPatch = "#A87FC4"
    const val methodDelete = "#E2554A"
    const val methodOther = "#8D8778"
    const val timingDns = "#6D9BC9"
    const val timingTcp = "#4FB3A3"
    const val timingTls = "#3AA981"
    const val timingTtfb = "#D9A514"
    const val timingDownload = "#EE8320"
    const val darkBackground = "#121110"
    const val darkSurface = "#1A1816"
    const val darkSurfaceRaised = "#23201C"
    const val darkBorder = "#35302A"
    const val darkText = "#EDEAE4"
    const val darkTextSecondary = "#A8A296"
    const val darkTextTertiary = "#6E695F"
    const val darkAccent = "#EE8320"
    const val lightBackground = "#FAF8F4"
    const val lightSurface = "#F2EFE8"
    const val lightSurfaceRaised = "#FFFFFF"
    const val lightBorder = "#E2DDD2"
    const val lightText = "#21201C"
    const val lightTextSecondary = "#57534A"
    const val lightTextTertiary = "#8B857A"
    const val lightAccent = "#E0761A"
    const val codeDarkKey = "#A8A296"
    const val codeDarkString = "#DE8D68"
    const val codeDarkNumber = "#7FB3E8"
    const val codeDarkBoolean = "#C08FD9"
    const val codeDarkNull = "#C08FD9"
    const val codeDarkHighlight = "#4D3D10"
    const val codeLightKey = "#57534A"
    const val codeLightString = "#B4552A"
    const val codeLightNumber = "#2B6CB0"
    const val codeLightBoolean = "#8548AB"
    const val codeLightNull = "#8548AB"
    const val codeLightHighlight = "#F5E5C0"
}

/**
 * Canonical Hakka geometry in dp/sp, shared with RN + web + iOS. Every
 * interactive control's height comes from [ControlHeight]; every page edge from
 * [Layout.gutter]. See DESIGN.md "One geometry".
 */
internal object GeneratedMetrics {
    object Spacing {
        const val xxs = 2
        const val xs = 4
        const val sm = 6
        const val md = 8
        const val ml = 10
        const val lg = 12
        const val ll = 14
        const val xl = 16
        const val xxl = 20
        const val xxxl = 24
    }

    object Radius {
        const val xs = 2
        const val sm = 4
        const val md = 6
        const val lg = 10
        const val xl = 14
        const val pill = 999
    }

    object FontSize {
        const val xxs = 9
        const val xs = 10
        const val sm = 12
        const val md = 13
        const val lg = 15
        const val xl = 16
        const val xxl = 18
        const val display = 22
        const val hero = 26
    }

    object ControlHeight {
        const val badge = 18
        const val chip = 24
        const val icon = 28
        const val md = 28
        const val field = 36
        const val nav = 40
        const val bar = 44
    }

    object Layout {
        const val gutter = 16
        const val cardPadding = 12
        const val sectionGap = 16
        const val rowGap = 8
    }
}
