// @generated by scripts/sync-design-tokens.mjs from design-tokens.json — do not edit.
// Run `just sync-tokens` after editing design-tokens.json.
/* eslint-disable */
export const status = {
  success: '#3AA981',
  info: '#6D9BC9',
  warning: '#D9A514',
  error: '#E2554A',
  pending: '#8D8778',
  on: '#FFFFFF',
  onWarm: '#171310',
} as const
export const method = {
  get: '#3AA981',
  post: '#EE8320',
  put: '#6D9BC9',
  patch: '#A87FC4',
  delete: '#E2554A',
  other: '#8D8778',
} as const
export const timing = {
  dns: '#6D9BC9',
  tcp: '#4FB3A3',
  tls: '#3AA981',
  ttfb: '#D9A514',
  download: '#EE8320',
} as const
export const paletteDark = {
  background: '#121110',
  surface: '#1A1816',
  surfaceRaised: '#23201C',
  border: '#35302A',
  text: '#EDEAE4',
  textSecondary: '#A8A296',
  textTertiary: '#6E695F',
  accent: '#EE8320',
} as const
export const paletteLight = {
  background: '#FAF8F4',
  surface: '#F2EFE8',
  surfaceRaised: '#FFFFFF',
  border: '#E2DDD2',
  text: '#21201C',
  textSecondary: '#57534A',
  textTertiary: '#8B857A',
  accent: '#E0761A',
} as const
export const codeDark = {
  string: '#DE8D68',
  number: '#7FB3E8',
  boolean: '#C08FD9',
  null: '#C08FD9',
  highlight: '#4D3D10',
} as const
export const codeLight = {
  string: '#B4552A',
  number: '#2B6CB0',
  boolean: '#8548AB',
  null: '#8548AB',
  highlight: '#F5E5C0',
} as const
