// @generated by scripts/sync-design-tokens.mjs from design-tokens.json — do not edit.
// Run `just sync-tokens` after editing design-tokens.json.
import SwiftUI

/// The demo app's own chrome palette, generated from `design-tokens.json`'s
/// `dark.*` entries so it cannot drift from the SDK it demonstrates.
///
/// This is generated rather than referenced because `HakkaTokens`
/// (`ios/Sources/UI/ThemeTokens.generated.swift`) is `internal` to the HakkaUI
/// module and deliberately not public SDK surface. The Example app is a separate
/// module consuming HakkaUI/HakkaNetwork/HakkaCommon as plain SPM products, so it
/// cannot see those symbols. Generating from the same source keeps the values
/// honest without widening the SDK's public API, and `just sync-tokens-check`
/// fails CI if this file falls out of sync.
enum DemoPalette {
    static let background = Color(red: 0.0706, green: 0.0667, blue: 0.0627)
    static let surface = Color(red: 0.1020, green: 0.0941, blue: 0.0863)
    static let surfaceRaised = Color(red: 0.1373, green: 0.1255, blue: 0.1098)
    static let border = Color(red: 0.2078, green: 0.1882, blue: 0.1647)
    static let text = Color(red: 0.9294, green: 0.9176, blue: 0.8941)
    static let textSecondary = Color(red: 0.6588, green: 0.6353, blue: 0.5882)
    static let textTertiary = Color(red: 0.4314, green: 0.4118, blue: 0.3725)
    static let accent = Color(red: 0.9333, green: 0.5137, blue: 0.1255)
}
