const GENERATED = '@generated by hakka-react-native'
const INSPECTOR_MODULE = 'hakkaInspector'
const DEFAULT_ANDROID_MAVEN_VERSION = '0.0.1'

/** Adds Hakka native capture and its optional Android inspector during Expo prebuild. */
function withHakka(config, options = {}) {
  const plugins = require('expo/config-plugins')
  const {
    withAppBuildGradle,
    withSettingsGradle,
    withAndroidManifest,
    withMainApplication,
    withGradleProperties,
    withDangerousMod,
  } = plugins

  if (options.android === false) return config

  const androidOptions = normalizeAndroidOptions(options)
  const usesPlayDelivery = androidOptions.uiDelivery === 'play'
  let next = withAppBuildGradle(config, (modConfig) => {
    let contents = addHakkaAndroidDependencies(modConfig.modResults.contents, androidOptions)
    contents = configureHakkaDynamicFeature(contents, usesPlayDelivery)
    modConfig.modResults.contents = contents
    return modConfig
  })

  if (withSettingsGradle) {
    next = withSettingsGradle(next, (modConfig) => {
      modConfig.modResults.contents = configureHakkaSettings(modConfig.modResults.contents, usesPlayDelivery)
      return modConfig
    })
  }
  if (withAndroidManifest) {
    next = withAndroidManifest(next, (modConfig) => {
      configureHakkaManifest(modConfig.modResults.manifest, usesPlayDelivery)
      return modConfig
    })
  }
  if (withMainApplication) {
    next = withMainApplication(next, (modConfig) => {
      modConfig.modResults.contents = configureSplitCompat(modConfig.modResults.contents, usesPlayDelivery)
      return modConfig
    })
  }
  if (usesPlayDelivery && withGradleProperties) {
    next = withGradleProperties(next, (modConfig) => {
      modConfig.modResults = configureHakkaGradleProperties(modConfig.modResults)
      return modConfig
    })
  }
  if (withDangerousMod) {
    next = withDangerousMod(next, [
      'android',
      async (modConfig) => {
        syncDynamicFeature(modConfig.modRequest.platformProjectRoot, androidOptions)
        return modConfig
      },
    ])
  }
  return next
}

function normalizeAndroidOptions(options) {
  const android = isObject(options.android) ? options.android : {}
  const hasUI = options.androidUI ?? android.ui ?? true
  const uiDelivery = hasUI ? String(options.uiDelivery ?? android.uiDelivery ?? 'play') : 'disabled'
  if (!['play', 'bundled', 'disabled'].includes(uiDelivery)) {
    throw new Error(`Invalid Hakka Android uiDelivery: ${uiDelivery}`)
  }
  return {
    version: String(options.androidMavenVersion ?? android.mavenVersion ?? DEFAULT_ANDROID_MAVEN_VERSION),
    performance: Boolean(options.androidPerformance ?? android.performance),
    uiDelivery,
  }
}

function addHakkaAndroidDependencies(contents, options) {
  const uiDelivery = options.uiDelivery ?? (options.ui === false ? 'disabled' : 'play')
  const dependencies = [['implementation', `com.noodleapps.hakka:hakka-network:${options.version}`]]
  const constraints = []
  if (options.performance) {
    dependencies.push(['implementation', `com.noodleapps.hakka:hakka-performance:${options.version}`])
  }
  if (uiDelivery === 'play') {
    dependencies.push(['implementation', 'com.google.android.play:feature-delivery:2.1.0'])
    constraints.push('androidx.activity:activity:1.12.1')
    constraints.push('androidx.collection:collection:1.5.0')
    constraints.push('androidx.compose.runtime:runtime-annotation:1.10.0')
    constraints.push('androidx.core:core-ktx:1.17.0')
    constraints.push('androidx.emoji2:emoji2:1.4.0')
    constraints.push('androidx.emoji2:emoji2-views-helper:1.4.0')
    constraints.push('androidx.lifecycle:lifecycle-runtime:2.9.4')
    constraints.push('androidx.savedstate:savedstate:1.3.2')
  } else if (uiDelivery === 'bundled') {
    dependencies.push(['implementation', `com.noodleapps.hakka:hakka-ui:${options.version}`])
  }

  let next = removeManagedDependencyLines(contents)
  const block = [
    `    // Hakka native capture dependencies (${GENERATED})`,
    ...dependencies.map(([configuration, coordinate]) => `    ${configuration}("${coordinate}")`),
    ...(constraints.length
      ? [
          `    // Hakka AndroidX feature alignment start (${GENERATED})`,
          '    constraints {',
          ...constraints.map((coordinate) => `        implementation("${coordinate}")`),
          '    }',
          `    // Hakka AndroidX feature alignment end (${GENERATED})`,
        ]
      : []),
  ].join('\n')
  const marker = 'dependencies {'
  const index = next.indexOf(marker)
  if (index < 0) return `${next.trimEnd()}\n\ndependencies {\n${block}\n}\n`
  const insertAt = index + marker.length
  return `${next.slice(0, insertAt)}\n${block}${next.slice(insertAt)}`
}

function removeManagedDependencyLines(contents) {
  const alignmentBlock = new RegExp(
    `^[ \\t]*// Hakka AndroidX feature alignment start \\(${GENERATED}\\)[\\s\\S]*?^[ \\t]*// Hakka AndroidX feature alignment end \\(${GENERATED}\\)[ \\t]*\\r?\\n?`,
    'gm',
  )
  const coordinate =
    '(?:com\\.noodleapps\\.hakka:(?:hakka-network(?:-noop)?|hakka-performance(?:-noop)?|hakka-ui):[^"\']+|com\\.google\\.android\\.play:feature-delivery:[^"\']+)'
  const dependency = new RegExp(
    `^[ \\t]*(?:api|implementation|debugImplementation|releaseImplementation|compileOnly)\\(["']${coordinate}["']\\)[ \\t]*\\r?\\n?`,
    'gm',
  )
  return contents
    .replace(alignmentBlock, '')
    .replace(dependency, '')
    .replace(
      new RegExp(`^[ \\t]*// Hakka native capture dependencies(?: \\(${GENERATED}\\))?[ \\t]*\\r?\\n?`, 'gm'),
      '',
    )
}

function configureHakkaDynamicFeature(contents, enabled) {
  const managedLine = new RegExp(
    `^[ \\t]*(?:android\\.)?dynamicFeatures \\+= \\[":${INSPECTOR_MODULE}"\\] // ${GENERATED}[ \\t]*\\r?\\n?`,
    'gm',
  )
  let next = contents.replace(managedLine, '')
  if (!enabled || new RegExp(`["']:${INSPECTOR_MODULE}["']`).test(next)) return next
  if (!next.includes('android {')) return next
  return `${next.trimEnd()}\nandroid.dynamicFeatures += [":${INSPECTOR_MODULE}"] // ${GENERATED}\n`
}

function configureHakkaSettings(contents, enabled) {
  const managedLine = new RegExp(`^[ \\t]*include ["']:${INSPECTOR_MODULE}["'] // ${GENERATED}[ \\t]*\\r?\\n?`, 'gm')
  const next = contents.replace(managedLine, '')
  if (!enabled || new RegExp(`include(?:\\s*\\(|\\s+)["']:${INSPECTOR_MODULE}["']`).test(next)) return next
  return `${next.trimEnd()}\ninclude ':${INSPECTOR_MODULE}' // ${GENERATED}\n`
}

function configureHakkaManifest(manifest, enabled) {
  const application = manifest.application?.[0]
  if (!application) return manifest
  const metadata = (application['meta-data'] ?? []).filter(
    (entry) => entry.$?.['android:name'] !== 'com.noodleapps.hakka.INSPECTOR_MODULE',
  )
  if (enabled) {
    metadata.push({
      $: {
        'android:name': 'com.noodleapps.hakka.INSPECTOR_MODULE',
        'android:value': INSPECTOR_MODULE,
      },
    })
  }
  application['meta-data'] = metadata
  return manifest
}

function configureHakkaGradleProperties(properties) {
  const next = properties.filter((entry) => entry.key !== 'android.nonTransitiveRClass')
  next.push({ type: 'property', key: 'android.nonTransitiveRClass', value: 'true' })
  return next
}

function configureSplitCompat(contents, enabled) {
  if (
    enabled &&
    (contents.includes(`Hakka SplitCompat start (${GENERATED})`) ||
      contents.includes(`SplitCompat.install(this) // ${GENERATED}`))
  ) {
    return contents
  }
  const block = new RegExp(
    `\\n(?:[ \\t]*\\r?\\n)?[ \\t]*// Hakka SplitCompat start \\(${GENERATED}\\)[\\s\\S]*?// Hakka SplitCompat end \\(${GENERATED}\\)\\r?\\n?`,
    'g',
  )
  let next = contents
    .replace(block, '\n')
    .replace(
      new RegExp(
        `^[ \\t]*com\\.google\\.android\\.play\\.core\\.splitcompat\\.SplitCompat\\.install\\(this\\);? // ${GENERATED}[ \\t]*\\r?\\n?`,
        'gm',
      ),
      '',
    )
    .replace(
      new RegExp(
        `\\nimport android\\.content\\.Context;? // ${GENERATED}\\r?\\nimport com\\.google\\.android\\.play\\.core\\.splitcompat\\.SplitCompat;? // ${GENERATED}\\r?\\n`,
        'g',
      ),
      '',
    )
    .replace(new RegExp(`^[ \\t]*import android\\.content\\.Context;? // ${GENERATED}[ \\t]*\\r?\\n?`, 'gm'), '')
    .replace(
      new RegExp(
        `^[ \\t]*import com\\.google\\.android\\.play\\.core\\.splitcompat\\.SplitCompat;? // ${GENERATED}[ \\t]*\\r?\\n?`,
        'gm',
      ),
      '',
    )
  if (!enabled || next.includes('SplitCompat.install(')) return next

  const isKotlin = /class\s+MainApplication\s*:\s*Application/.test(next)
  if (/attachBaseContext\s*\(/.test(next)) {
    const existingOverride = isKotlin
      ? /(override\s+fun\s+attachBaseContext\((\w+):\s*(?:android\.content\.)?Context\)\s*\{[\s\S]*?super\.attachBaseContext\(\2\))/
      : /(protected\s+void\s+attachBaseContext\((?:android\.content\.)?Context\s+(\w+)\)\s*\{[\s\S]*?super\.attachBaseContext\(\2\);)/
    if (!existingOverride.test(next)) {
      throw new Error('Hakka found attachBaseContext but could not safely add SplitCompat')
    }
    const install = isKotlin
      ? `\n    com.google.android.play.core.splitcompat.SplitCompat.install(this) // ${GENERATED}`
      : `\n    com.google.android.play.core.splitcompat.SplitCompat.install(this); // ${GENERATED}`
    return next.replace(existingOverride, `$1${install}`)
  }
  const classPattern = isKotlin
    ? /(class\s+MainApplication\s*:\s*Application[^{]*{)/
    : /(class\s+MainApplication\s+extends\s+Application[^{]*{)/
  if (!classPattern.test(next)) {
    throw new Error('Hakka could not add SplitCompat to MainApplication')
  }
  const method = isKotlin
    ? `\n\n  // Hakka SplitCompat start (${GENERATED})\n  override fun attachBaseContext(base: android.content.Context) {\n    super.attachBaseContext(base)\n    com.google.android.play.core.splitcompat.SplitCompat.install(this) // ${GENERATED}\n  }\n  // Hakka SplitCompat end (${GENERATED})`
    : `\n\n  // Hakka SplitCompat start (${GENERATED})\n  @Override\n  protected void attachBaseContext(android.content.Context base) {\n    super.attachBaseContext(base);\n    com.google.android.play.core.splitcompat.SplitCompat.install(this); // ${GENERATED}\n  }\n  // Hakka SplitCompat end (${GENERATED})`
  return next.replace(classPattern, `$1${method}`)
}

function dynamicFeatureGradle(version) {
  return `// ${GENERATED}\nplugins {\n    id "com.android.dynamic-feature"\n    id "org.jetbrains.kotlin.android"\n}\n\nandroid {\n    namespace "com.noodleapps.hakka.inspector"\n    compileSdk rootProject.ext.compileSdkVersion\n\n    defaultConfig {\n        minSdk rootProject.ext.minSdkVersion\n    }\n\n    buildTypes {\n        release {\n            proguardFiles "proguard-rules.pro"\n        }\n    }\n\n    packaging {\n        resources.excludes += "META-INF/androidx.*.version"\n    }\n}\n\ndependencies {\n    implementation project(":app")\n    implementation("com.noodleapps.hakka:hakka-ui:${version}")\n}\n`
}

function dynamicFeatureManifest() {
  return `<!-- ${GENERATED} -->\n<manifest xmlns:android="http://schemas.android.com/apk/res/android"\n    xmlns:dist="http://schemas.android.com/apk/distribution"\n    xmlns:tools="http://schemas.android.com/tools">\n    <dist:module dist:instant="false" dist:title="@string/app_name">\n        <dist:delivery><dist:on-demand /></dist:delivery>\n        <dist:fusing dist:include="false" />\n    </dist:module>\n    <application android:hasCode="true">\n        <activity\n            android:name="com.noodleapps.hakka.ui.HakkaActivity"\n            android:theme="@android:style/Theme.DeviceDefault.Light.NoActionBar"\n            tools:replace="android:theme" />\n        <activity\n            android:name="com.noodleapps.hakka.ui.DetailActivity"\n            android:theme="@android:style/Theme.DeviceDefault.Light.NoActionBar"\n            tools:replace="android:theme" />\n        <activity\n            android:name="com.noodleapps.hakka.ui.SettingsActivity"\n            android:theme="@android:style/Theme.DeviceDefault.Light.NoActionBar"\n            tools:replace="android:theme" />\n        <provider android:name="androidx.core.content.FileProvider">\n            <meta-data\n                android:name="android.support.FILE_PROVIDER_PATHS"\n                android:resource="@xml/hakka_inspector_file_paths"\n                tools:replace="android:resource" />\n        </provider>\n    </application>\n</manifest>\n`
}

function dynamicFeaturePaths() {
  return `<!-- ${GENERATED} -->\n<paths xmlns:android="http://schemas.android.com/apk/res/android">\n    <cache-path name="hakka_exports" path="hakka-exports/" />\n</paths>\n`
}

function dynamicFeatureProguard() {
  return `# ${GENERATED}\n-keep,allowoptimization class com.noodleapps.hakka.ui.HakkaUI {\n    public static com.noodleapps.hakka.ui.HakkaUI getInstance(android.content.Context);\n    public com.noodleapps.hakka.ui.HakkaUI attach(com.noodleapps.hakka.LogStore);\n    public com.noodleapps.hakka.ui.HakkaUI attachInterceptor(com.noodleapps.hakka.HakkaInterceptor);\n    public com.noodleapps.hakka.ui.HakkaUI attachPluginProvider(kotlin.jvm.functions.Function0);\n    public void present(android.app.Activity, java.lang.String, kotlin.jvm.functions.Function1);\n    public void hide();\n    public java.util.List captureStorageSnapshots(java.util.Set);\n    public kotlin.jvm.functions.Function0 subscribeStructuredLogs(kotlin.jvm.functions.Function1);\n}\n`
}

function syncDynamicFeature(projectRoot, options) {
  const path = require('node:path')
  const feature = path.join(projectRoot, INSPECTOR_MODULE)
  const files = [
    [path.join(feature, 'build.gradle'), dynamicFeatureGradle(options.version)],
    [path.join(feature, 'proguard-rules.pro'), dynamicFeatureProguard()],
    [path.join(feature, 'src/main/AndroidManifest.xml'), dynamicFeatureManifest()],
    [path.join(projectRoot, 'app/src/main/res/xml/hakka_inspector_file_paths.xml'), dynamicFeaturePaths()],
  ]
  if (options.uiDelivery === 'play') {
    for (const [file, contents] of files) writeOwnedFile(file, contents)
  } else {
    for (const [file] of files) removeOwnedFile(file)
  }
}

function writeOwnedFile(file, contents) {
  const fs = require('node:fs')
  const path = require('node:path')
  if (fs.existsSync(file)) {
    const existing = fs.readFileSync(file, 'utf8')
    if (existing === contents) return
    if (!existing.split(/\r?\n/, 1)[0].includes(GENERATED)) {
      throw new Error(`Hakka will not overwrite app-owned file: ${file}`)
    }
  }
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, contents)
}

function removeOwnedFile(file) {
  const fs = require('node:fs')
  if (!fs.existsSync(file)) return
  const existing = fs.readFileSync(file, 'utf8')
  if (existing.split(/\r?\n/, 1)[0].includes(GENERATED)) fs.unlinkSync(file)
}

function isObject(value) {
  return value != null && typeof value === 'object' && !Array.isArray(value)
}

module.exports = withHakka
module.exports.default = withHakka
module.exports.normalizeAndroidOptions = normalizeAndroidOptions
module.exports.addHakkaAndroidDependencies = addHakkaAndroidDependencies
module.exports.configureHakkaDynamicFeature = configureHakkaDynamicFeature
module.exports.configureHakkaSettings = configureHakkaSettings
module.exports.configureHakkaManifest = configureHakkaManifest
module.exports.configureHakkaGradleProperties = configureHakkaGradleProperties
module.exports.configureSplitCompat = configureSplitCompat
module.exports.dynamicFeatureGradle = dynamicFeatureGradle
module.exports.dynamicFeatureManifest = dynamicFeatureManifest
module.exports.dynamicFeaturePaths = dynamicFeaturePaths
module.exports.dynamicFeatureProguard = dynamicFeatureProguard
module.exports.syncDynamicFeature = syncDynamicFeature
