import HakkaUI

/// Short call-site aliases onto `HakkaUI.HakkaMetrics` — the same geometry
/// scale RN, web, and Android draw from (generated by
/// `scripts/sync-design-tokens.mjs` from `design-tokens.json`, see
/// `ios/Sources/UI/ThemeTokens.generated.swift`). No raw numbers live here;
/// this file only shortens `HakkaMetrics.Spacing.md` to `Spacing.md` so the
/// desktop's ~200 call sites don't repeat the `HakkaMetrics.` prefix.
///
/// `Theme` (ios/Sources/UI/Theme.swift) wraps the same constants for the iOS
/// inspector, but `Theme` itself is gated behind `#if canImport(UIKit)` and
/// isn't visible to this module — see swiftui-patterns.md. Reach for
/// `HakkaMetrics` directly (or these aliases) instead.
typealias Spacing = HakkaMetrics.Spacing
typealias Radius = HakkaMetrics.Radius
typealias FontSize = HakkaMetrics.FontSize
typealias ControlHeight = HakkaMetrics.ControlHeight
typealias Layout = HakkaMetrics.Layout
